# Generated by Django 4.1.1 on 2022-09-19 06:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline1', models.CharField(blank=True, max_length=128)),
                ('addressline2', models.CharField(blank=True, max_length=128)),
                ('addressline3', models.CharField(blank=True, max_length=128)),
                ('City', models.CharField(blank=True, max_length=128)),
                ('State', models.CharField(blank=True, max_length=128)),
                ('Country', models.CharField(blank=True, max_length=128)),
                ('Zipcode', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('company', models.CharField(blank=True, max_length=128)),
                ('phone_office', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('phone_cell', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('phone_direct', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactor_name', models.CharField(blank=True, max_length=128)),
                ('tube_id_in', models.CharField(blank=True, max_length=128)),
                ('tube_id_mm', models.CharField(blank=True, max_length=128)),
                ('is_there_ferrule_insert_in_tube', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='is_there_ferrule_insert_in_tube')),
                ('ferrule_length', models.CharField(blank=True, max_length=128)),
                ('ferrule_id', models.CharField(blank=True, max_length=128)),
                ('tube_material_of_tubes', models.CharField(blank=True, max_length=128)),
                ('tube_material_of_raws', models.CharField(blank=True, max_length=128)),
                ('tube_material_of_thermo', models.CharField(blank=True, max_length=128)),
                ('tube_material_of_supports', models.CharField(blank=True, max_length=128)),
                ('tube_material_of_plugs', models.CharField(blank=True, max_length=128)),
                ('tube_material_of_coolent_tubes', models.CharField(blank=True, max_length=128)),
                ('tube_spacing_in_or_pitch', models.CharField(blank=True, max_length=128)),
                ('tube_spacing_mm_or_pitch', models.CharField(blank=True, max_length=128)),
                ('tube_spacing_proof_document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('total_tube_length', models.CharField(blank=True, max_length=128)),
                ('top_tube_sheet_thickness', models.CharField(blank=True, max_length=128)),
                ('bottom_tube_sheet_thickness', models.CharField(blank=True, max_length=128)),
                ('tube_protude_out_of_top_tube_sheet', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='tube_protude_out_of_top_tube_sheet')),
                ('tube_protude_out_of_bottom_tube_sheet', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='tube_protude_out_of_bottom_tube_sheet')),
                ('top_dome_removable', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='top_dome_removable')),
                ('top_inlet_accessible', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='top_inlet_accessible')),
                ('top_inlet_impingment_plate', models.BooleanField(choices=[(True, 'yes'), (False, 'No')], default='False', verbose_name='top_inlet_impingment_plate')),
                ('any_projections_on_tube_sheet_describe', models.TextField(blank=True)),
                ('tube_sheet_material', models.CharField(blank=True, max_length=128)),
                ('dom_material', models.CharField(blank=True, max_length=128)),
                ('reactor_tube_sheet_drawings', models.FileField(blank=True, null=True, upload_to='images/')),
                ('reactor_elevation_view_drawings', models.FileField(blank=True, null=True, upload_to='images/')),
                ('other_drawings', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_location', models.CharField(blank=True, max_length=128)),
                ('plant_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('plant_address', models.ManyToManyField(to='client.address')),
                ('reactor', models.ManyToManyField(to='client.reactor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=128)),
                ('comman_name', models.CharField(blank=True, max_length=128)),
                ('alternate_name', models.CharField(blank=True, max_length=128)),
                ('key_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('parent_company', models.CharField(blank=True, max_length=128)),
                ('chemical', models.CharField(blank=True, max_length=128)),
                ('chemical_unit', models.CharField(blank=True, max_length=128)),
                ('unit_name', models.CharField(blank=True, max_length=128)),
                ('reactor_per_each_unit', models.CharField(blank=True, max_length=128)),
                ('former_name', models.CharField(blank=True, max_length=128)),
                ('official_address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='official_address', to='client.address')),
                ('plant', models.ManyToManyField(to='client.plant')),
                ('plantentrance_address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantentrance_address', to='client.address')),
                ('reactor', models.ManyToManyField(to='client.reactor')),
                ('shipping_address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='client.address')),
            ],
        ),
    ]
